/** Map a file path to a Monaco editor language id. */

const BY_EXTENSION: Record<string, string> = {
	ts: 'typescript',
	tsx: 'typescript',
	mts: 'typescript',
	cts: 'typescript',
	js: 'javascript',
	jsx: 'javascript',
	mjs: 'javascript',
	cjs: 'javascript',
	json: 'json',
	jsonc: 'json',
	json5: 'json',
	css: 'css',
	scss: 'scss',
	sass: 'scss',
	less: 'less',
	html: 'html',
	htm: 'html',
	xhtml: 'html',
	md: 'markdown',
	markdown: 'markdown',
	mdx: 'markdown',
	py: 'python',
	pyw: 'python',
	pyi: 'python',
	rb: 'ruby',
	php: 'php',
	java: 'java',
	kt: 'kotlin',
	kts: 'kotlin',
	scala: 'scala',
	go: 'go',
	rs: 'rust',
	c: 'c',
	h: 'c',
	cpp: 'cpp',
	cc: 'cpp',
	cxx: 'cpp',
	hpp: 'cpp',
	hh: 'cpp',
	hxx: 'cpp',
	cs: 'csharp',
	fs: 'fsharp',
	fsx: 'fsharp',
	swift: 'swift',
	m: 'objective-c',
	mm: 'cpp',
	r: 'r',
	R: 'r',
	sql: 'sql',
	mysql: 'mysql',
	pgsql: 'pgsql',
	sh: 'shell',
	bash: 'shell',
	zsh: 'shell',
	fish: 'shell',
	ps1: 'powershell',
	psm1: 'powershell',
	psd1: 'powershell',
	bat: 'bat',
	cmd: 'bat',
	yaml: 'yaml',
	yml: 'yaml',
	toml: 'ini',
	ini: 'ini',
	cfg: 'ini',
	conf: 'ini',
	xml: 'xml',
	svg: 'xml',
	plist: 'xml',
	vue: 'html',
	svelte: 'html',
	graphql: 'graphql',
	gql: 'graphql',
	proto: 'protobuf',
	dockerfile: 'dockerfile',
	dockerignore: 'dockerfile',
	makefile: 'plaintext',
	cmake: 'plaintext',
	gradle: 'groovy',
	groovy: 'groovy',
	dart: 'dart',
	lua: 'lua',
	perl: 'perl',
	pl: 'perl',
	pm: 'perl',
	clj: 'clojure',
	cljs: 'clojure',
	edn: 'clojure',
	ex: 'elixir',
	exs: 'elixir',
	erl: 'plaintext',
	hrl: 'plaintext',
	hs: 'plaintext',
	lhs: 'plaintext',
	ml: 'plaintext',
	mli: 'plaintext',
	nim: 'plaintext',
	zig: 'plaintext',
	v: 'plaintext',
	vhdl: 'plaintext',
	verilog: 'plaintext',
	sv: 'plaintext',
	tf: 'plaintext',
	hcl: 'plaintext',
	sol: 'solidity',
	wasm: 'plaintext',
	wat: 'plaintext',
	txt: 'plaintext',
	log: 'plaintext',
	csv: 'plaintext',
	tsv: 'plaintext',
	env: 'ini',
	gitignore: 'plaintext',
	gitattributes: 'plaintext',
	editorconfig: 'ini',
	npmrc: 'ini',
	prettierrc: 'json',
	eslintrc: 'json',
	babelrc: 'json',
};

const BY_BASENAME: Record<string, string> = {
	dockerfile: 'dockerfile',
	containerfile: 'dockerfile',
	makefile: 'plaintext',
	gnumakefile: 'plaintext',
	'cmakelists.txt': 'plaintext',
	'cargo.toml': 'ini',
	'cargo.lock': 'ini',
	'go.mod': 'plaintext',
	'go.sum': 'plaintext',
	'package.json': 'json',
	'package-lock.json': 'json',
	'tsconfig.json': 'json',
	'jsconfig.json': 'json',
	'composer.json': 'json',
	'pyproject.toml': 'ini',
	'requirements.txt': 'plaintext',
	'gemfile': 'ruby',
	'rakefile': 'ruby',
	'procfile': 'plaintext',
	'.env': 'ini',
	'.env.local': 'ini',
	'.env.development': 'ini',
	'.env.production': 'ini',
	'.gitignore': 'plaintext',
	'.gitattributes': 'plaintext',
	'.editorconfig': 'ini',
	'.npmrc': 'ini',
	'.prettierrc': 'json',
	'.eslintrc': 'json',
	'.eslintrc.json': 'json',
	'.babelrc': 'json',
	'readme': 'markdown',
	'readme.md': 'markdown',
	'license': 'plaintext',
	'licence': 'plaintext',
};

/** Human label for status / UI (not a marketing tag). */
export function languageLabel(languageId: string): string {
	const labels: Record<string, string> = {
		typescript: 'TypeScript',
		javascript: 'JavaScript',
		json: 'JSON',
		css: 'CSS',
		scss: 'SCSS',
		less: 'Less',
		html: 'HTML',
		markdown: 'Markdown',
		python: 'Python',
		ruby: 'Ruby',
		php: 'PHP',
		java: 'Java',
		kotlin: 'Kotlin',
		scala: 'Scala',
		go: 'Go',
		rust: 'Rust',
		c: 'C',
		cpp: 'C++',
		csharp: 'C#',
		fsharp: 'F#',
		swift: 'Swift',
		'objective-c': 'Objective-C',
		r: 'R',
		sql: 'SQL',
		mysql: 'MySQL',
		pgsql: 'PostgreSQL',
		shell: 'Shell',
		powershell: 'PowerShell',
		bat: 'Batch',
		yaml: 'YAML',
		ini: 'INI',
		xml: 'XML',
		graphql: 'GraphQL',
		protobuf: 'Protobuf',
		dockerfile: 'Dockerfile',
		groovy: 'Groovy',
		dart: 'Dart',
		lua: 'Lua',
		perl: 'Perl',
		clojure: 'Clojure',
		elixir: 'Elixir',
		solidity: 'Solidity',
		plaintext: 'Plain Text',
	};
	return labels[languageId] ?? languageId;
}

export function languageFromPath(path: string): string {
	const normalized = path.replace(/\\/g, '/');
	const base = (normalized.split('/').pop() || '').toLowerCase();

	if (BY_BASENAME[base]) return BY_BASENAME[base];

	// multi-dot specials: .eslintrc.js, file.d.ts
	if (base.endsWith('.d.ts')) return 'typescript';
	if (base.endsWith('.d.mts') || base.endsWith('.d.cts')) return 'typescript';
	if (base.endsWith('.cjs') || base.endsWith('.mjs')) return 'javascript';

	const dot = base.lastIndexOf('.');
	if (dot <= 0 || dot === base.length - 1) {
		// extensionless scripts often shell
		if (/^(install|configure|bootstrap)$/i.test(base)) return 'shell';
		return 'plaintext';
	}

	const ext = base.slice(dot + 1);
	if (BY_EXTENSION[ext]) return BY_EXTENSION[ext];
	// case-sensitive R
	if (ext === 'r') return 'r';
	return 'plaintext';
}
